### PR TITLE
Provide RubyInstaller with builtin MSYS2 toolchain

### PR DESCRIPTION
**Pull request by larskanis**
This adds a second package called "rubybundle" which exports ~100MB sized exe and 7z files. See the [artifacts on Appveyor](https://ci.appveyor.com/project/larskanis/rubyinstaller2-hbuor/build/1.0.65). This avoids extra download and setup of MSYS2 for the user and could be interesting for offline installations.

I'm not sure about the name "rubybundle". Has someone a better name?

Although it already works well for me, it probably needs some more fine tuning. It currently ships a fully arranged MSYS2 environment with private keys. They should be better generated on the target machine.

### CODE REVIEW

**Comment by larskanis** [comment]
@luislavena @jonforums @Azolo @MSP-Greg Any opinions to adding this?

**Comment by Azolo** [comment]
DevKit was originally separate because it was possible to have multiple Ruby installations use the same DevKit "installation".

In retrospect, having a package like this isn't a terrible idea. But, it is another thing to maintain and another spot for confusion. I would make sure you have a suggested installation package and explain the differences.

But, that's just my pessimistic outlook and suggestions based on that outlook. Don't feel bad for not putting too much weight on my advice.

**Comment by MSP-Greg** [comment]
@larskanis @Azolo Sorry for the delay.

I'm somewhat conflicted about embedding MSYS2 in the ruby dir structure.

I've spent decades working with DOS/Windows, and probably weeks working on OSX.  So I understand the 'oneclick install` mentality, which is tricky to provide for extension gems.

I wonder if it will cause confusion for users when/if they decide to upgrade ruby.

I can't help but think that new Windows ruby users fall largely in two groups.  The first, people with some programming experience that would understand the issues.  The second, new users learning programming, and probably also installing Rails.

If anything, I think a package that supplies most of (or all?) the MSYS2/MinGW files needed for a Rails install might be one for consideration...

Sorry for going sideways...

**Comment by larskanis** [comment]
Thanks for sharing your thoughts!

In the last two days I resurrected the idea of having a installer package with all default MSYS2 dependencies. It's because I need it at work, so that I would like to make it "official". If you like, you can try it out from [Appveyor artifacts](https://ci.appveyor.com/project/larskanis/rubyinstaller2-hbuor).

> I wonder if it will cause confusion for users when/if they decide to upgrade ruby.

This was the main technical issue I had to solve. How shall updating MSYS2 work, if it's bundled into the installer? I think it's mostly solved now: MSYS2 is handled as a selectable component, which is automatically deselected on an update install with MSYS2 already present. MSYS2 is decoupled more or less from Ruby after installation, so that it can be updated separately by `pacman`, `ridk install` or so. The installer informs how the MSYS2 setup is handled and RubyInstaller with and without MSYS2 can be mixed at will.

> In retrospect, having a package like this isn't a terrible idea. But, it is another thing to maintain and another spot for confusion. I would make sure you have a suggested installation package and explain the differences.

This is true. It is a second way to install MSYS2, but the current way through `ridk install` can not really be removed. I still doubt whether RubyBundle is a good name. Maybe just "RubyInstaller with MSYS2" and "RubyInstaller without MSYS2"? This is possibly more expressive.

> If anything, I think a package that supplies most of (or all?) the MSYS2/MinGW files needed for a Rails install might be one for consideration...

For sure, that should be the case for typical rails apps! Otherwise I would tread it as a bug. I don't try to support each and every possible gem, but the most typical gems should just work.

My plan is to post about RubyBundle on rubyinstaller.org as an experimental feature and if it works well, to add it to every future release.

**Comment by MSP-Greg** [comment]
I think this may solve a lot of issues for people with new installs.

The only issue I came across recently was working on Appveyor with a gem that used OpenSSL, and was testing against both 2.4 (1.0.2) & 2.5/trunk (1.1.0).  Maybe docs/install 'info' could include some info about it?  I think (at present) OpenSSL is the only package that may cause issues?  I worked around it, but for those less familiar...

Thanks again, Greg

**Comment by larskanis** [comment]
> a gem that used OpenSSL, and was testing against both 2.4 (1.0.2) & 2.5/trunk (1.1.0). Maybe docs/install 'info' could include some info about it?

Which gem is it? Is it about issue #60? What should be documented?

**Comment by larskanis** [comment]
@luislavena @jonforums @Azolo @MSP-Greg @Kjarrigan  Do you have an opinion about the name of the new baby with builtin MSYS2 toolchain component?

Both installer variants are still the same, with the only difference that one has a selectable install component called "MSYS2 development toolchain" and the other doesn't. Both can be mixed and matched at will.

So my proposals are:
1. "RubyInstaller" and "RubyBundle": This is how I call it currently in the code. The downside is that "RubyBundle" isn't "RubyInstaller" and people are used to use "RubyInstaller" and I would like to make the MSYS-bundled version more or less the default on rubyinstaller.org. It also sounds less meaningful to me. Filenames would be `rubyinstaller-2.5.0-3-x64.exe` and `rubybundle-2.5.0-3-x64.exe` .
2. "RubyInstaller-lite" and "RubyInstaller-full": I don't want to change the filename of the executable, so filenames could be `rubyinstaller-2.5.0-3-x64.exe` and `rubyinstaller-full-2.5.0-3-x64.exe` .
3. "RubyInstaller" and "RubyInstaller-with-MSYS2" or "-with-DevKit": Filenames could be `rubyinstaller-2.5.0-3-x64.exe` and `rubyinstaller-with-msys2-2.5.0-3-x64.exe` .

What do you think?

**Comment by MSP-Greg** [comment]
I vote 3, as to 'MSYS2' or 'DevKit', that's a tough choice.

I'm not sure how well known the term 'MSYS2' is outside of people that have used it.  then again, maybe people should be familiar with it.

Also, having used Notepad++ for a while, rather than '-with-devkit', maybe use '+devkit' (or MSYS2)?

**Comment by MSP-Greg** [comment]
@larskanis

> Which gem is it? Is it about issue #60? What should be documented?

Sorry for the delay, I thought I knew of three, but I have not remembered the third.  The two are EventMachine & Puma.

I assume that if one is using 2.4, they should be compiled with 1.0.2, if one is using 2.5, 1.1.0 should be used.  I haven't actually used the exe installer for quite a while, so I don't know if it accounts for this 
 issue.

FYI, new OpenSSL releases on Tuesday.

Thanks, Greg

**Comment by Azolo** [comment]
@larskanis Honestly, if you want it to be the default then just name it `rubyinstaller`

Name the installer without the tool chain something like `msys2-ruby`.

Not every one will be happy, but if it's what you want then do it. It's not like you can't change it if it doesn't work out.

**Comment by Kjarrigan** [comment]
I'm for option 3 as well. Its more clear than the rest but I agree to Azolo as well. Just make it the default and add an _Rubyinstaller-without-Devkit_ as opt-out. I think the most people looking for Rubyinstaller have eiter no clue what the Devkit-thingy is, but experience rather quickly problems when installing gems that depend on it, or they know what it is and are able to decide if they might reuse an existing msys setup. In all the years I installed Ruby under Windows (which wasn't that often but) I always needed the DevKit and usually it was annoying the do two setups to just get Ruby running so I could continue installing my gems.

**Comment by larskanis** [comment]
Thanks again for discussing the naming issue! As you can see in the [release post](https://rubyinstaller.org/2018/03/29/rubyinstaller-2.5.1-1-and-2.4.4-1-released.html), I stepped forward and published the RubyInstaller-Devkit versions together with the new Ruby versions 2.5.1 and 2.4.4.

Plus character [didn't work](https://github.com/oneclick/rubyinstaller2/commit/c93e7765bda9b806bc32701a5dedabe53e67e8bb), so that I kept backward compatibility by using `rubyinstaller-<version>.exe` and named the new thing `rubyinstaller-devkit-<version>.exe`.

Keep fingers crossed for that it works for everyone!

**Pull request merged**
