### PR TITLE
Add dbm to test/test_stdlib.rb

### PR DESCRIPTION
**Pull request by MSP-Greg**
See [rubyinstaller2-packages PR 6]( https://github.com/oneclick/rubyinstaller2-packages/pull/6)

### CODE REVIEW

**Comment by MSP-Greg** [comment]
My fault.  Should have waited for the other commit...

**Comment by MSP-Greg** [comment]
Is libgdbm_compat-4.dll included in dll's?

**Comment by MSP-Greg** [comment]
I think I've got a pretty good idea what's being done here vs 'packages', but I haven't exhaustively gone thru it since the split...

If I (or you) add `libgdbm_compat-4.dll` to [rubyinstaller-2.3.4.files](https://github.com/oneclick/rubyinstaller2/blob/master/recipes/sandbox/rubyinstaller-2.3.4.files), [rubyinstaller-2.4.1.files](https://github.com/oneclick/rubyinstaller2/blob/master/recipes/sandbox/rubyinstaller-2.4.1.files) and [rubyinstaller-2.5.0.files](https://github.com/oneclick/rubyinstaller2/blob/master/recipes/sandbox/rubyinstaller-2.5.0.files), should appveyor pass?

Or, is something else required?

**Comment by larskanis** [comment]
Yes, this is probably the required change. I only didn't had the time to verify this, today.

**Comment by MSP-Greg** [comment]
Wasn't sure, so I just checked the Appveyor logs, and the 1.10 package is being added.  I'll do a PR soon...

**Pull request merged**
